### PR TITLE
Swift 3.0 Migration

### PR DESCRIPTION
**Pull request by alexpovh**
dshb didn't install for me via brew on 10.12, looks like it can't build swift 2 anymore

SMCKit: https://github.com/beltex/SMCKit/pull/27
SystemKit: https://github.com/beltex/SystemKit/pull/25
CommandLine: https://github.com/jatoben/CommandLine/pull/83

### CODE REVIEW

**Comment by alexpovh** [comment]
I have one for SMCKit as well - https://github.com/beltex/SMCKit/pull/27
Will likely need to fix tests for SystemKit and CommandLine.

dshb didn't install for me via brew on 10.12, looks like it can't build swift 2 anymore

**Comment by ilovezfs** [comment]
ping on this

**Comment by ilovezfs** [comment]
build appears to be failing with HEAD https://gist.github.com/ilovezfs/501cb85c702a9e001e122293890ba65c

**Comment by alexpovh** [comment]
It has dependency on this https://github.com/beltex/SystemKit/pull/25. After it's merged, libs directory submodules need to be updated to point to swift 3 versions and then it should work!

**Comment by ealeksandrov** [comment]
Anyone wants to clone&run - I've updated this branch to use Swift 3 forks of SCMKit, SystemKit and latest version of CommandLineKit: https://github.com/ealeksandrov/dshb/tree/swift3.0.

```
git clone --recursive https://github.com/ealeksandrov/dshb
cd dshb
make install
```

Thanks @alexpovh and @perfaram for your PRs.

**Comment by ilovezfs** [comment]
@ealeksandrov yes that compiles on 10.11 with Xcode 8.2.1 and on 10.12 with Xcode 8.3.3.

@beltex what needs to be done to get @ealeksandrov's changes merged?

**Comment by ilovezfs** [comment]
@beltex Gentle ping on this. We're bottling for macOS 10.13 High Sierra in Homebrew now and still don't have a Sierra bottle. Also, we've lost the ability to rebuild dshb at all since Homebrew has dropped Yosemite support, and our El Capitan CI uses Xcode 8.2.1.

**Comment by ilovezfs** [comment]
@alexpovh have you looked at refreshing this for Xcode 9 and for https://github.com/jatoben/CommandLine/pull/78 ?

**Comment by beltex** [comment]
Thanks so much for this @alexpovh! And so sorry about the super late response on this folks!

**Pull request merged**
